from .mcdonalds_profile import get_code_handler
from .mcdonalds_profile import del_code_handler
from .mcdonalds_profile import archived_codes
from .change_language import settings_change_language_handler
